//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qcontrol.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qcontrol.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must not exceed 500 characters..
        /// </summary>
        public static string Branch_Address_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Address_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arabic branch name must not exceed 100 characters..
        /// </summary>
        public static string Branch_ArabicName_MaxLength {
            get {
                return ResourceManager.GetString("Branch_ArabicName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area must not exceed 100 characters..
        /// </summary>
        public static string Branch_Area_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Area_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is required..
        /// </summary>
        public static string Branch_Authentication_Required {
            get {
                return ResourceManager.GetString("Branch_Authentication_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city must not exceed 100 characters..
        /// </summary>
        public static string Branch_City_MaxLength {
            get {
                return ResourceManager.GetString("Branch_City_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch cannot be deleted because it has related waiting areas or displays..
        /// </summary>
        public static string Branch_Delete_HasRelatedData {
            get {
                return ResourceManager.GetString("Branch_Delete_HasRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English branch name must not exceed 100 characters..
        /// </summary>
        public static string Branch_EnglishName_MaxLength {
            get {
                return ResourceManager.GetString("Branch_EnglishName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The governorate must not exceed 100 characters..
        /// </summary>
        public static string Branch_Governorate_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Governorate_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid branch id is required..
        /// </summary>
        public static string Branch_Id_Required {
            get {
                return ResourceManager.GetString("Branch_Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another branch already uses this IP address..
        /// </summary>
        public static string Branch_IPAddress_AlreadyExists {
            get {
                return ResourceManager.GetString("Branch_IPAddress_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address must be a valid IPv4 or IPv6 address..
        /// </summary>
        public static string Branch_IPAddress_Invalid {
            get {
                return ResourceManager.GetString("Branch_IPAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address must not exceed 45 characters..
        /// </summary>
        public static string Branch_IPAddress_MaxLength {
            get {
                return ResourceManager.GetString("Branch_IPAddress_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address is required..
        /// </summary>
        public static string Branch_IPAddress_Required {
            get {
                return ResourceManager.GetString("Branch_IPAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude must not exceed 50 characters..
        /// </summary>
        public static string Branch_Latitude_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Latitude_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude must not exceed 50 characters..
        /// </summary>
        public static string Branch_Longitude_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Longitude_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one branch name, Arabic or English, is required..
        /// </summary>
        public static string Branch_Name_Required {
            get {
                return ResourceManager.GetString("Branch_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch could not be found..
        /// </summary>
        public static string Branch_NotFound {
            get {
                return ResourceManager.GetString("Branch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be at least 1..
        /// </summary>
        public static string Branch_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be at least 1..
        /// </summary>
        public static string Branch_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageSize_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100..
        /// </summary>
        public static string Branch_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageSize_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user profile could not be found..
        /// </summary>
        public static string Login_ActorProfile_NotFound {
            get {
                return ResourceManager.GetString("Login_ActorProfile_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username, email, or password..
        /// </summary>
        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 200 characters..
        /// </summary>
        public static string Login_Password_MaxLength {
            get {
                return ResourceManager.GetString("Login_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email must not exceed 200 characters..
        /// </summary>
        public static string Login_UserNameOrEmail_MaxLength {
            get {
                return ResourceManager.GetString("Login_UserNameOrEmail_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email is required..
        /// </summary>
        public static string Login_UserNameOrEmail_Required {
            get {
                return ResourceManager.GetString("Login_UserNameOrEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role is assigned to this user..
        /// </summary>
        public static string Login_UserRoles_NotFound {
            get {
                return ResourceManager.GetString("Login_UserRoles_NotFound", resourceCulture);
            }
        }
    }
}
