//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qcontrol.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qcontrol.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must not exceed 500 characters..
        /// </summary>
        public static string Branch_Address_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Address_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arabic branch name must not exceed 100 characters..
        /// </summary>
        public static string Branch_ArabicName_MaxLength {
            get {
                return ResourceManager.GetString("Branch_ArabicName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area must not exceed 100 characters..
        /// </summary>
        public static string Branch_Area_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Area_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is required..
        /// </summary>
        public static string Branch_Authentication_Required {
            get {
                return ResourceManager.GetString("Branch_Authentication_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city must not exceed 100 characters..
        /// </summary>
        public static string Branch_City_MaxLength {
            get {
                return ResourceManager.GetString("Branch_City_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch cannot be permanently deleted because it has related waiting areas or displays..
        /// </summary>
        public static string Branch_PermanentDelete_HasRelatedData {
            get {
                return ResourceManager.GetString("Branch_PermanentDelete_HasRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English branch name must not exceed 100 characters..
        /// </summary>
        public static string Branch_EnglishName_MaxLength {
            get {
                return ResourceManager.GetString("Branch_EnglishName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The governorate must not exceed 100 characters..
        /// </summary>
        public static string Branch_Governorate_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Governorate_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid branch id is required..
        /// </summary>
        public static string Branch_Id_Required {
            get {
                return ResourceManager.GetString("Branch_Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another branch already uses this IP address..
        /// </summary>
        public static string Branch_IPAddress_AlreadyExists {
            get {
                return ResourceManager.GetString("Branch_IPAddress_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address must be a valid IPv4 or IPv6 address..
        /// </summary>
        public static string Branch_IPAddress_Invalid {
            get {
                return ResourceManager.GetString("Branch_IPAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address must not exceed 45 characters..
        /// </summary>
        public static string Branch_IPAddress_MaxLength {
            get {
                return ResourceManager.GetString("Branch_IPAddress_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch IP address is required..
        /// </summary>
        public static string Branch_IPAddress_Required {
            get {
                return ResourceManager.GetString("Branch_IPAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude must not exceed 50 characters..
        /// </summary>
        public static string Branch_Latitude_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Latitude_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude must not exceed 50 characters..
        /// </summary>
        public static string Branch_Longitude_MaxLength {
            get {
                return ResourceManager.GetString("Branch_Longitude_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one branch name, Arabic or English, is required..
        /// </summary>
        public static string Branch_Name_Required {
            get {
                return ResourceManager.GetString("Branch_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch could not be found..
        /// </summary>
        public static string Branch_NotFound {
            get {
                return ResourceManager.GetString("Branch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be at least 1..
        /// </summary>
        public static string Branch_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be at least 1..
        /// </summary>
        public static string Branch_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageSize_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100..
        /// </summary>
        public static string Branch_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("Branch_Pagination_PageSize_Max", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication is required..
        /// </summary>
        public static string WaitingArea_Authentication_Required {
            get {
                return ResourceManager.GetString("WaitingArea_Authentication_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The audio device must not exceed 100 characters..
        /// </summary>
        public static string WaitingArea_AudioDevice_MaxLength {
            get {
                return ResourceManager.GetString("WaitingArea_AudioDevice_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected branch could not be found..
        /// </summary>
        public static string WaitingArea_Branch_NotFound {
            get {
                return ResourceManager.GetString("WaitingArea_Branch_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid branch id is required..
        /// </summary>
        public static string WaitingArea_BranchId_Required {
            get {
                return ResourceManager.GetString("WaitingArea_BranchId_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The control device must not exceed 100 characters..
        /// </summary>
        public static string WaitingArea_ControlDevice_MaxLength {
            get {
                return ResourceManager.GetString("WaitingArea_ControlDevice_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The waiting area was created successfully..
        /// </summary>
        public static string WaitingArea_Create_Success {
            get {
                return ResourceManager.GetString("WaitingArea_Create_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The waiting area cannot be permanently deleted because it contains windows..
        /// </summary>
        public static string WaitingArea_PermanentDelete_HasWindows {
            get {
                return ResourceManager.GetString("WaitingArea_PermanentDelete_HasWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The descriptive name must not exceed 100 characters..
        /// </summary>
        public static string WaitingArea_DescriptiveName_MaxLength {
            get {
                return ResourceManager.GetString("WaitingArea_DescriptiveName_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The route waiting area id must match the request waiting area id..
        /// </summary>
        public static string WaitingArea_Id_Mismatch {
            get {
                return ResourceManager.GetString("WaitingArea_Id_Mismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid waiting area id is required..
        /// </summary>
        public static string WaitingArea_Id_Required {
            get {
                return ResourceManager.GetString("WaitingArea_Id_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The waiting area could not be found..
        /// </summary>
        public static string WaitingArea_NotFound {
            get {
                return ResourceManager.GetString("WaitingArea_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Another waiting area in this branch already uses this number..
        /// </summary>
        public static string WaitingArea_Number_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("WaitingArea_Number_AlreadyExistsInBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The waiting area number must be greater than zero..
        /// </summary>
        public static string WaitingArea_Number_Required {
            get {
                return ResourceManager.GetString("WaitingArea_Number_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page number must be at least 1..
        /// </summary>
        public static string WaitingArea_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("WaitingArea_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page size must be at least 1..
        /// </summary>
        public static string WaitingArea_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("WaitingArea_Pagination_PageSize_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100..
        /// </summary>
        public static string WaitingArea_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("WaitingArea_Pagination_PageSize_Max", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The waiting area was updated successfully..
        /// </summary>
        public static string WaitingArea_Update_Success {
            get {
                return ResourceManager.GetString("WaitingArea_Update_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication is required..
        /// </summary>
        public static string Window_Authentication_Required {
            get {
                return ResourceManager.GetString("Window_Authentication_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window was created successfully..
        /// </summary>
        public static string Window_Create_Success {
            get {
                return ResourceManager.GetString("Window_Create_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window descriptive name must not exceed 100 characters..
        /// </summary>
        public static string Window_DescriptiveName_MaxLength {
            get {
                return ResourceManager.GetString("Window_DescriptiveName_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The route window id must match the request window id..
        /// </summary>
        public static string Window_Id_Mismatch {
            get {
                return ResourceManager.GetString("Window_Id_Mismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid window id is required..
        /// </summary>
        public static string Window_Id_Required {
            get {
                return ResourceManager.GetString("Window_Id_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window IP address already exists in this waiting area..
        /// </summary>
        public static string Window_IPAddress_AlreadyExistsInWaitingArea {
            get {
                return ResourceManager.GetString("Window_IPAddress_AlreadyExistsInWaitingArea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window IP address must be a valid IPv4 or IPv6 address..
        /// </summary>
        public static string Window_IPAddress_Invalid {
            get {
                return ResourceManager.GetString("Window_IPAddress_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window IP address must not exceed 45 characters..
        /// </summary>
        public static string Window_IPAddress_MaxLength {
            get {
                return ResourceManager.GetString("Window_IPAddress_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window could not be found..
        /// </summary>
        public static string Window_NotFound {
            get {
                return ResourceManager.GetString("Window_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window number already exists in this waiting area..
        /// </summary>
        public static string Window_Number_AlreadyExistsInWaitingArea {
            get {
                return ResourceManager.GetString("Window_Number_AlreadyExistsInWaitingArea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window number must not exceed 20 characters..
        /// </summary>
        public static string Window_Number_MaxLength {
            get {
                return ResourceManager.GetString("Window_Number_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window number is required..
        /// </summary>
        public static string Window_Number_Required {
            get {
                return ResourceManager.GetString("Window_Number_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page number must be at least 1..
        /// </summary>
        public static string Window_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("Window_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page size must be at least 1..
        /// </summary>
        public static string Window_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("Window_Pagination_PageSize_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100..
        /// </summary>
        public static string Window_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("Window_Pagination_PageSize_Max", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window cannot be permanently deleted because related records exist..
        /// </summary>
        public static string Window_PermanentDelete_HasRelatedRecords {
            get {
                return ResourceManager.GetString("Window_PermanentDelete_HasRelatedRecords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window was permanently deleted successfully..
        /// </summary>
        public static string Window_PermanentDelete_Success {
            get {
                return ResourceManager.GetString("Window_PermanentDelete_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The window was updated successfully..
        /// </summary>
        public static string Window_Update_Success {
            get {
                return ResourceManager.GetString("Window_Update_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected waiting area could not be found..
        /// </summary>
        public static string Window_WaitingArea_NotFound {
            get {
                return ResourceManager.GetString("Window_WaitingArea_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A valid waiting area id is required..
        /// </summary>
        public static string Window_WaitingAreaId_Required {
            get {
                return ResourceManager.GetString("Window_WaitingAreaId_Required", resourceCulture);
            }
        }

        public static string Terminal_AlreadyActive {
            get {
                return ResourceManager.GetString("Terminal_AlreadyActive", resourceCulture);
            }
        }
        
        public static string Terminal_Authentication_Required {
            get {
                return ResourceManager.GetString("Terminal_Authentication_Required", resourceCulture);
            }
        }
        
        public static string Terminal_Create_Success {
            get {
                return ResourceManager.GetString("Terminal_Create_Success", resourceCulture);
            }
        }
        
        public static string Terminal_Id_Mismatch {
            get {
                return ResourceManager.GetString("Terminal_Id_Mismatch", resourceCulture);
            }
        }
        
        public static string Terminal_Id_Required {
            get {
                return ResourceManager.GetString("Terminal_Id_Required", resourceCulture);
            }
        }
        
        public static string Terminal_IPAddress_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("Terminal_IPAddress_AlreadyExistsInBranch", resourceCulture);
            }
        }
        
        public static string Terminal_IPAddress_Invalid {
            get {
                return ResourceManager.GetString("Terminal_IPAddress_Invalid", resourceCulture);
            }
        }
        
        public static string Terminal_IPAddress_MaxLength {
            get {
                return ResourceManager.GetString("Terminal_IPAddress_MaxLength", resourceCulture);
            }
        }
        
        public static string Terminal_IPAddress_Required {
            get {
                return ResourceManager.GetString("Terminal_IPAddress_Required", resourceCulture);
            }
        }
        
        public static string Terminal_NotFound {
            get {
                return ResourceManager.GetString("Terminal_NotFound", resourceCulture);
            }
        }
        
        public static string Terminal_Number_AlreadyExistsInWindow {
            get {
                return ResourceManager.GetString("Terminal_Number_AlreadyExistsInWindow", resourceCulture);
            }
        }
        
        public static string Terminal_Number_MaxLength {
            get {
                return ResourceManager.GetString("Terminal_Number_MaxLength", resourceCulture);
            }
        }
        
        public static string Terminal_Number_Required {
            get {
                return ResourceManager.GetString("Terminal_Number_Required", resourceCulture);
            }
        }
        
        public static string Terminal_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("Terminal_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }
        
        public static string Terminal_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("Terminal_Pagination_PageSize_Invalid", resourceCulture);
            }
        }
        
        public static string Terminal_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("Terminal_Pagination_PageSize_Max", resourceCulture);
            }
        }
        
        public static string Terminal_PermanentDelete_HasRelatedRecords {
            get {
                return ResourceManager.GetString("Terminal_PermanentDelete_HasRelatedRecords", resourceCulture);
            }
        }
        
        public static string Terminal_PermanentDelete_Success {
            get {
                return ResourceManager.GetString("Terminal_PermanentDelete_Success", resourceCulture);
            }
        }
        
        public static string Terminal_SerialNo_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("Terminal_SerialNo_AlreadyExistsInBranch", resourceCulture);
            }
        }
        
        public static string Terminal_SerialNo_MaxLength {
            get {
                return ResourceManager.GetString("Terminal_SerialNo_MaxLength", resourceCulture);
            }
        }
        
        public static string Terminal_SerialNo_Required {
            get {
                return ResourceManager.GetString("Terminal_SerialNo_Required", resourceCulture);
            }
        }
        
        public static string Terminal_Type_MaxLength {
            get {
                return ResourceManager.GetString("Terminal_Type_MaxLength", resourceCulture);
            }
        }
        
        public static string Terminal_Type_Required {
            get {
                return ResourceManager.GetString("Terminal_Type_Required", resourceCulture);
            }
        }
        
        public static string Terminal_Update_Success {
            get {
                return ResourceManager.GetString("Terminal_Update_Success", resourceCulture);
            }
        }
        
        public static string Terminal_Window_NotFound {
            get {
                return ResourceManager.GetString("Terminal_Window_NotFound", resourceCulture);
            }
        }
        
        public static string Terminal_WindowId_Required {
            get {
                return ResourceManager.GetString("Terminal_WindowId_Required", resourceCulture);
            }
        }
        
        public static string Display_AlreadyActive {
            get {
                return ResourceManager.GetString("Display_AlreadyActive", resourceCulture);
            }
        }
        
        public static string Display_Authentication_Required {
            get {
                return ResourceManager.GetString("Display_Authentication_Required", resourceCulture);
            }
        }
        
        public static string Display_Branch_NotFound {
            get {
                return ResourceManager.GetString("Display_Branch_NotFound", resourceCulture);
            }
        }
        
        public static string Display_BranchId_Required {
            get {
                return ResourceManager.GetString("Display_BranchId_Required", resourceCulture);
            }
        }
        
        public static string Display_Create_Success {
            get {
                return ResourceManager.GetString("Display_Create_Success", resourceCulture);
            }
        }
        
        public static string Display_Id_Mismatch {
            get {
                return ResourceManager.GetString("Display_Id_Mismatch", resourceCulture);
            }
        }
        
        public static string Display_Id_Required {
            get {
                return ResourceManager.GetString("Display_Id_Required", resourceCulture);
            }
        }
        
        public static string Display_IPAddress_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("Display_IPAddress_AlreadyExistsInBranch", resourceCulture);
            }
        }
        
        public static string Display_IPAddress_Invalid {
            get {
                return ResourceManager.GetString("Display_IPAddress_Invalid", resourceCulture);
            }
        }
        
        public static string Display_IPAddress_MaxLength {
            get {
                return ResourceManager.GetString("Display_IPAddress_MaxLength", resourceCulture);
            }
        }
        
        public static string Display_IPAddress_Required {
            get {
                return ResourceManager.GetString("Display_IPAddress_Required", resourceCulture);
            }
        }
        
        public static string Display_NotFound {
            get {
                return ResourceManager.GetString("Display_NotFound", resourceCulture);
            }
        }
        
        public static string Display_Number_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("Display_Number_AlreadyExistsInBranch", resourceCulture);
            }
        }
        
        public static string Display_Number_MaxLength {
            get {
                return ResourceManager.GetString("Display_Number_MaxLength", resourceCulture);
            }
        }
        
        public static string Display_Number_Required {
            get {
                return ResourceManager.GetString("Display_Number_Required", resourceCulture);
            }
        }
        
        public static string Display_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("Display_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }
        
        public static string Display_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("Display_Pagination_PageSize_Invalid", resourceCulture);
            }
        }
        
        public static string Display_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("Display_Pagination_PageSize_Max", resourceCulture);
            }
        }
        
        public static string Display_PermanentDelete_HasDisplayWindowLinks {
            get {
                return ResourceManager.GetString("Display_PermanentDelete_HasDisplayWindowLinks", resourceCulture);
            }
        }
        
        public static string Display_PermanentDelete_HasRelatedRecords {
            get {
                return ResourceManager.GetString("Display_PermanentDelete_HasRelatedRecords", resourceCulture);
            }
        }
        
        public static string Display_PermanentDelete_Success {
            get {
                return ResourceManager.GetString("Display_PermanentDelete_Success", resourceCulture);
            }
        }
        
        public static string Display_SerialNo_AlreadyExistsInBranch {
            get {
                return ResourceManager.GetString("Display_SerialNo_AlreadyExistsInBranch", resourceCulture);
            }
        }
        
        public static string Display_SerialNo_MaxLength {
            get {
                return ResourceManager.GetString("Display_SerialNo_MaxLength", resourceCulture);
            }
        }
        
        public static string Display_SerialNo_Required {
            get {
                return ResourceManager.GetString("Display_SerialNo_Required", resourceCulture);
            }
        }
        
        public static string Display_Type_MaxLength {
            get {
                return ResourceManager.GetString("Display_Type_MaxLength", resourceCulture);
            }
        }
        
        public static string Display_Type_Required {
            get {
                return ResourceManager.GetString("Display_Type_Required", resourceCulture);
            }
        }
        
        public static string Display_UniqueConstraint_Conflict {
            get {
                return ResourceManager.GetString("Display_UniqueConstraint_Conflict", resourceCulture);
            }
        }
        
        public static string Display_Update_Success {
            get {
                return ResourceManager.GetString("Display_Update_Success", resourceCulture);
            }
        }

        public static string DisplayWindow_Assign_AlreadyLinked {
            get {
                return ResourceManager.GetString("DisplayWindow_Assign_AlreadyLinked", resourceCulture);
            }
        }

        public static string DisplayWindow_Assign_DifferentBranch {
            get {
                return ResourceManager.GetString("DisplayWindow_Assign_DifferentBranch", resourceCulture);
            }
        }

        public static string DisplayWindow_Assign_Success {
            get {
                return ResourceManager.GetString("DisplayWindow_Assign_Success", resourceCulture);
            }
        }

        public static string DisplayWindow_Authentication_Required {
            get {
                return ResourceManager.GetString("DisplayWindow_Authentication_Required", resourceCulture);
            }
        }

        public static string DisplayWindow_Display_NotFound {
            get {
                return ResourceManager.GetString("DisplayWindow_Display_NotFound", resourceCulture);
            }
        }

        public static string DisplayWindow_DisplayId_Required {
            get {
                return ResourceManager.GetString("DisplayWindow_DisplayId_Required", resourceCulture);
            }
        }

        public static string DisplayWindow_Pagination_PageNumber_Invalid {
            get {
                return ResourceManager.GetString("DisplayWindow_Pagination_PageNumber_Invalid", resourceCulture);
            }
        }

        public static string DisplayWindow_Pagination_PageSize_Invalid {
            get {
                return ResourceManager.GetString("DisplayWindow_Pagination_PageSize_Invalid", resourceCulture);
            }
        }

        public static string DisplayWindow_Pagination_PageSize_Max {
            get {
                return ResourceManager.GetString("DisplayWindow_Pagination_PageSize_Max", resourceCulture);
            }
        }

        public static string DisplayWindow_Unassign_LinkNotFound {
            get {
                return ResourceManager.GetString("DisplayWindow_Unassign_LinkNotFound", resourceCulture);
            }
        }

        public static string DisplayWindow_Unassign_Success {
            get {
                return ResourceManager.GetString("DisplayWindow_Unassign_Success", resourceCulture);
            }
        }

        public static string DisplayWindow_Window_NotFound {
            get {
                return ResourceManager.GetString("DisplayWindow_Window_NotFound", resourceCulture);
            }
        }

        public static string DisplayWindow_WindowId_Required {
            get {
                return ResourceManager.GetString("DisplayWindow_WindowId_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user profile could not be found..
        /// </summary>
        public static string Login_ActorProfile_NotFound {
            get {
                return ResourceManager.GetString("Login_ActorProfile_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username, email, or password..
        /// </summary>
        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 200 characters..
        /// </summary>
        public static string Login_Password_MaxLength {
            get {
                return ResourceManager.GetString("Login_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email must not exceed 200 characters..
        /// </summary>
        public static string Login_UserNameOrEmail_MaxLength {
            get {
                return ResourceManager.GetString("Login_UserNameOrEmail_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email is required..
        /// </summary>
        public static string Login_UserNameOrEmail_Required {
            get {
                return ResourceManager.GetString("Login_UserNameOrEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role is assigned to this user..
        /// </summary>
        public static string Login_UserRoles_NotFound {
            get {
                return ResourceManager.GetString("Login_UserRoles_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch address is required.
        /// </summary>
        public static string Branch_Address_Required {
            get {
                return ResourceManager.GetString("Branch_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch is already active.
        /// </summary>
        public static string Branch_AlreadyActive {
            get {
                return ResourceManager.GetString("Branch_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch is already inactive.
        /// </summary>
        public static string Branch_AlreadyInactive {
            get {
                return ResourceManager.GetString("Branch_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arabic branch name is required.
        /// </summary>
        public static string Branch_ArabicName_Required {
            get {
                return ResourceManager.GetString("Branch_ArabicName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch area is required.
        /// </summary>
        public static string Branch_Area_Required {
            get {
                return ResourceManager.GetString("Branch_Area_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch city is required.
        /// </summary>
        public static string Branch_City_Required {
            get {
                return ResourceManager.GetString("Branch_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch was deactivated successfully.
        /// </summary>
        public static string Branch_Deactivate_Success {
            get {
                return ResourceManager.GetString("Branch_Deactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English branch name is required.
        /// </summary>
        public static string Branch_EnglishName_Required {
            get {
                return ResourceManager.GetString("Branch_EnglishName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch governorate is required.
        /// </summary>
        public static string Branch_Governorate_Required {
            get {
                return ResourceManager.GetString("Branch_Governorate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be between -90 and 90.
        /// </summary>
        public static string Branch_Latitude_Invalid {
            get {
                return ResourceManager.GetString("Branch_Latitude_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180 and 180.
        /// </summary>
        public static string Branch_Longitude_Invalid {
            get {
                return ResourceManager.GetString("Branch_Longitude_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch was permanently deleted successfully.
        /// </summary>
        public static string Branch_PermanentDelete_Success {
            get {
                return ResourceManager.GetString("Branch_PermanentDelete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch was reactivated successfully.
        /// </summary>
        public static string Branch_Reactivate_Success {
            get {
                return ResourceManager.GetString("Branch_Reactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another request. Refresh and try again.
        /// </summary>
        public static string Concurrency_Conflict {
            get {
                return ResourceManager.GetString("Concurrency_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display is already inactive.
        /// </summary>
        public static string Display_AlreadyInactive {
            get {
                return ResourceManager.GetString("Display_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display was deactivated successfully.
        /// </summary>
        public static string Display_Deactivate_Success {
            get {
                return ResourceManager.GetString("Display_Deactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display was reactivated successfully.
        /// </summary>
        public static string Display_Reactivate_Success {
            get {
                return ResourceManager.GetString("Display_Reactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record must be inactive before permanent deletion.
        /// </summary>
        public static string PermanentDelete_RequiresInactive {
            get {
                return ResourceManager.GetString("PermanentDelete_RequiresInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row version is invalid.
        /// </summary>
        public static string RowVersion_Invalid {
            get {
                return ResourceManager.GetString("RowVersion_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row version is required.
        /// </summary>
        public static string RowVersion_Required {
            get {
                return ResourceManager.GetString("RowVersion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text must not exceed 200 characters.
        /// </summary>
        public static string SearchTerm_MaxLength {
            get {
                return ResourceManager.GetString("SearchTerm_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terminal is already inactive.
        /// </summary>
        public static string Terminal_AlreadyInactive {
            get {
                return ResourceManager.GetString("Terminal_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terminal was deactivated successfully.
        /// </summary>
        public static string Terminal_Deactivate_Success {
            get {
                return ResourceManager.GetString("Terminal_Deactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terminal was reactivated successfully.
        /// </summary>
        public static string Terminal_Reactivate_Success {
            get {
                return ResourceManager.GetString("Terminal_Reactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting area is already active.
        /// </summary>
        public static string WaitingArea_AlreadyActive {
            get {
                return ResourceManager.GetString("WaitingArea_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting area is already inactive.
        /// </summary>
        public static string WaitingArea_AlreadyInactive {
            get {
                return ResourceManager.GetString("WaitingArea_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting area was deactivated successfully.
        /// </summary>
        public static string WaitingArea_Deactivate_Success {
            get {
                return ResourceManager.GetString("WaitingArea_Deactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting area was permanently deleted successfully.
        /// </summary>
        public static string WaitingArea_PermanentDelete_Success {
            get {
                return ResourceManager.GetString("WaitingArea_PermanentDelete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting area was reactivated successfully.
        /// </summary>
        public static string WaitingArea_Reactivate_Success {
            get {
                return ResourceManager.GetString("WaitingArea_Reactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is already active.
        /// </summary>
        public static string Window_AlreadyActive {
            get {
                return ResourceManager.GetString("Window_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is already inactive.
        /// </summary>
        public static string Window_AlreadyInactive {
            get {
                return ResourceManager.GetString("Window_AlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window was deactivated successfully.
        /// </summary>
        public static string Window_Deactivate_Success {
            get {
                return ResourceManager.GetString("Window_Deactivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window was reactivated successfully.
        /// </summary>
        public static string Window_Reactivate_Success {
            get {
                return ResourceManager.GetString("Window_Reactivate_Success", resourceCulture);
            }
        }
    }
}
