// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QControl.infrastructure.Persistence;

#nullable disable

namespace Qcontrol.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformWriteDbContext))]
    partial class PlatformWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QControl.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.ToTable("Branch", null, t =>
                        {
                            t.HasCheckConstraint("CK_Branch_ArabicName_Required", "NULLIF(LTRIM(RTRIM([ArabicName])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Branch_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Branch_EnglishName_Required", "NULLIF(LTRIM(RTRIM([EnglishName])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Branch_IPAddress_NotBlank", "NULLIF(LTRIM(RTRIM([IPAddress])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Branch_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.BranchAdvertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("BranchId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("BranchId", "IsActive", "DisplayOrder");

                    b.ToTable("BranchAdvertisement", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchAdvertisement_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_BranchAdvertisement_DisplayOrder_Range", "(([DisplayOrder] >= 1 AND [DisplayOrder] <= 20) OR ([DisplayOrder] >= 1001 AND [DisplayOrder] <= 1020))");

                            t.HasCheckConstraint("CK_BranchAdvertisement_ImagePath_NotBlank", "NULLIF(LTRIM(RTRIM([ImagePath])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_BranchAdvertisement_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.BranchBranding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MainColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.ToTable("BranchBranding", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchBranding_BackgroundColor_Format", "[BackgroundColor] IS NULL OR ([BackgroundColor] COLLATE Latin1_General_BIN2 LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' AND LEN([BackgroundColor]) = 7)");

                            t.HasCheckConstraint("CK_BranchBranding_MainColor_Format", "[MainColor] IS NULL OR ([MainColor] COLLATE Latin1_General_BIN2 LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' AND LEN([MainColor]) = 7)");

                            t.HasCheckConstraint("CK_BranchBranding_SecondaryColor_Format", "[SecondaryColor] IS NULL OR ([SecondaryColor] COLLATE Latin1_General_BIN2 LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' AND LEN([SecondaryColor]) = 7)");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "BranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("BranchId", "IPAddress")
                        .IsUnique();

                    b.HasIndex("BranchId", "Number")
                        .IsUnique();

                    b.HasIndex("BranchId", "SerialNo")
                        .IsUnique();

                    b.ToTable("Display", null, t =>
                        {
                            t.HasCheckConstraint("CK_Display_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Display_IPAddress_NotBlank", "NULLIF(LTRIM(RTRIM([IPAddress])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Display_Number_NotBlank", "NULLIF(LTRIM(RTRIM([Number])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Display_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Display_SerialNo_NotBlank", "NULLIF(LTRIM(RTRIM([SerialNo])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Display_Type_NotBlank", "NULLIF(LTRIM(RTRIM([Type])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.DisplayWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WindowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DisplayId");

                    b.HasIndex("WindowId");

                    b.HasIndex("DisplayId", "WindowId")
                        .IsUnique();

                    b.ToTable("DisplayWindow", (string)null);
                });

            modelBuilder.Entity("QControl.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.ToTable("Location", null, t =>
                        {
                            t.HasCheckConstraint("CK_Location_Address_Required", "NULLIF(LTRIM(RTRIM([Address])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Location_Area_Required", "NULLIF(LTRIM(RTRIM([Area])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Location_City_Required", "NULLIF(LTRIM(RTRIM([City])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Location_Governorate_Required", "NULLIF(LTRIM(RTRIM([Governorate])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Location_Latitude_Range", "[Latitude] >= -90 AND [Latitude] <= 90");

                            t.HasCheckConstraint("CK_Location_Longitude_Range", "[Longitude] >= -180 AND [Longitude] <= 180");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArabicUserMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnglishUserMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HasReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsClientInputRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTicketIssuable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfTicketCopies")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("RangeEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("RangePrefix")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("RangeStartNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RestoredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("WaitingDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ParentServiceId");

                    b.HasIndex("ArabicName", "ParentServiceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Service_ArabicName_ParentServiceId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("EnglishName", "ParentServiceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Service_EnglishName_ParentServiceId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("ParentServiceId", "OrderNo")
                        .HasDatabaseName("IX_Service_ParentServiceId_OrderNo");

                    b.ToTable("Service", null, t =>
                        {
                            t.HasCheckConstraint("CK_Service_ArabicName_NotBlank", "LEN(LTRIM(RTRIM([ArabicName]))) > 0");

                            t.HasCheckConstraint("CK_Service_EnglishName_NotBlank", "LEN(LTRIM(RTRIM([EnglishName]))) > 0");

                            t.HasCheckConstraint("CK_Service_NoOfTicketCopies_NullOrPositive", "[NoOfTicketCopies] IS NULL OR [NoOfTicketCopies] > 0");

                            t.HasCheckConstraint("CK_Service_OrderNo_NonNegative", "[OrderNo] >= 0");

                            t.HasCheckConstraint("CK_Service_Priority_NonNegative", "[Priority] >= 0");

                            t.HasCheckConstraint("CK_Service_RangeEnd_NullOrGreaterOrEqualStart", "[RangeStartNumber] IS NULL OR [RangeEndNumber] IS NULL OR [RangeEndNumber] >= [RangeStartNumber]");

                            t.HasCheckConstraint("CK_Service_RangeEnd_NullOrNonNegative", "[RangeEndNumber] IS NULL OR [RangeEndNumber] >= 0");

                            t.HasCheckConstraint("CK_Service_RangePrefix_NullOrNotBlank", "[RangePrefix] IS NULL OR LEN(LTRIM(RTRIM([RangePrefix]))) > 0");

                            t.HasCheckConstraint("CK_Service_RangeStart_NullOrNonNegative", "[RangeStartNumber] IS NULL OR [RangeStartNumber] >= 0");

                            t.HasCheckConstraint("CK_Service_TicketIssuable_Settings_Required", "[IsTicketIssuable] = 0 OR ([RangePrefix] IS NOT NULL AND LEN(LTRIM(RTRIM([RangePrefix]))) > 0 AND [RangeStartNumber] IS NOT NULL AND [RangeEndNumber] IS NOT NULL AND [WaitingDuration] IS NOT NULL AND [NoOfTicketCopies] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Service_WaitingDuration_NullOrNonNegative", "[WaitingDuration] IS NULL OR [WaitingDuration] >= 0");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceId", "ImageType")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceImage_ServiceId_ImageType_LogoIcon")
                        .HasFilter("[ImageType] IN (1, 2)");

                    b.HasIndex("ServiceId", "ImageType", "DisplayOrder");

                    b.ToTable("ServiceImage", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceImage_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_ServiceImage_ImagePath_NotBlank", "LEN(LTRIM(RTRIM([ImagePath]))) > 0");

                            t.HasCheckConstraint("CK_ServiceImage_ImageType_Valid", "[ImageType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ArabicName")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceWorkflows_ArabicName");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("EnglishName")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceWorkflows_EnglishName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ServiceWorkflows_IsActive");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.ToTable("ServiceWorkflows", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceWorkflows_ArabicName_NotBlank", "LEN(LTRIM(RTRIM([ArabicName]))) > 0");

                            t.HasCheckConstraint("CK_ServiceWorkflows_EnglishName_NotBlank", "LEN(LTRIM(RTRIM([EnglishName]))) > 0");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceWorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceWorkflowId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServiceWorkflowSteps_ServiceId");

                    b.HasIndex("ServiceWorkflowId")
                        .HasDatabaseName("IX_ServiceWorkflowSteps_ServiceWorkflowId");

                    b.HasIndex("ServiceWorkflowId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceWorkflowSteps_ServiceWorkflowId_StepOrder");

                    b.ToTable("ServiceWorkflowSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiceWorkflowSteps_StepOrder_Positive", "[StepOrder] > 0");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WindowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("WindowId");

                    b.HasIndex("BranchId", "IPAddress")
                        .IsUnique();

                    b.HasIndex("BranchId", "SerialNo")
                        .IsUnique();

                    b.HasIndex("WindowId", "BranchId");

                    b.HasIndex("WindowId", "Number")
                        .IsUnique();

                    b.ToTable("Terminal", null, t =>
                        {
                            t.HasCheckConstraint("CK_Terminal_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Terminal_IPAddress_NotBlank", "NULLIF(LTRIM(RTRIM([IPAddress])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Terminal_Number_NotBlank", "NULLIF(LTRIM(RTRIM([Number])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Terminal_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Terminal_SerialNo_NotBlank", "NULLIF(LTRIM(RTRIM([SerialNo])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Terminal_Type_NotBlank", "NULLIF(LTRIM(RTRIM([Type])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.WaitingArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioDevice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ControlDevice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DescriptiveName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("BranchId", "Number")
                        .IsUnique();

                    b.ToTable("WaitingArea", null, t =>
                        {
                            t.HasCheckConstraint("CK_WaitingArea_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_WaitingArea_Number_Positive", "[Number] > 0");

                            t.HasCheckConstraint("CK_WaitingArea_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Entities.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DescriptiveName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EnableDirectCall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableTicketBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ReactivatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReactivatedOnUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("WaitingAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeactivatedByApplicationUserId");

                    b.HasIndex("LastModifiedByApplicationUserId");

                    b.HasIndex("ReactivatedByApplicationUserId");

                    b.HasIndex("WaitingAreaId");

                    b.HasIndex("WaitingAreaId", "BranchId");

                    b.HasIndex("WaitingAreaId", "IPAddress")
                        .IsUnique()
                        .HasDatabaseName("UX_Window_WaitingAreaId_IPAddress")
                        .HasFilter("[IPAddress] IS NOT NULL");

                    b.HasIndex("WaitingAreaId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_Window_WaitingAreaId_Number");

                    b.ToTable("Window", null, t =>
                        {
                            t.HasCheckConstraint("CK_Window_DeactivationAudit_Pair", "(([DeactivatedOnUtc] IS NULL AND [DeactivatedByApplicationUserId] IS NULL) OR ([DeactivatedOnUtc] IS NOT NULL AND [DeactivatedByApplicationUserId] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Window_IPAddress_NotBlank", "[IPAddress] IS NULL OR NULLIF(LTRIM(RTRIM([IPAddress])), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Window_Number_NotBlank", "NULLIF(LTRIM(RTRIM([Number])), N'') IS NOT NULL");

                            t.HasCheckConstraint("CK_Window_ReactivationAudit_Pair", "(([ReactivatedOnUtc] IS NULL AND [ReactivatedByApplicationUserId] IS NULL) OR ([ReactivatedOnUtc] IS NOT NULL AND [ReactivatedByApplicationUserId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("QControl.Domain.Identity.TechnicalAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("TechnicalAdmin", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PasswordChangedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationUser_Email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationUser_UserName");

                    b.ToTable("ApplicationUser", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.ApplicationUserBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("IX_ApplicationUserBranch_ApplicationUserId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_ApplicationUserBranch_BranchId");

                    b.HasIndex("ApplicationUserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationUserBranch_ApplicationUserId_BranchId");

                    b.ToTable("ApplicationUserBranch", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.BranchAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchAdmin_ApplicationUserId");

                    b.ToTable("BranchAdmin", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ApplicationUserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserRole_ApplicationUserId_RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("QControl.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.BranchAdvertisement", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithMany("Advertisements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.BranchBranding", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithOne("Branding")
                        .HasForeignKey("QControl.Domain.Entities.BranchBranding", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Display", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithMany("Displays")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.DisplayWindow", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QControl.Domain.Entities.Display", "Display")
                        .WithMany("DisplayWindows")
                        .HasForeignKey("DisplayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QControl.Domain.Entities.Window", "Window")
                        .WithMany("DisplayWindows")
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("Display");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Location", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithOne("Location")
                        .HasForeignKey("QControl.Domain.Entities.Location", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Service", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QControl.Domain.Entities.Service", "ParentService")
                        .WithMany("Children")
                        .HasForeignKey("ParentServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ParentService");
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceImage", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QControl.Domain.Entities.Service", "Service")
                        .WithMany("Images")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceWorkflow", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceWorkflowStep", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QControl.Domain.Entities.ServiceWorkflow", "ServiceWorkflow")
                        .WithMany("Steps")
                        .HasForeignKey("ServiceWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceWorkflow");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Terminal", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QControl.Domain.Entities.Window", "Window")
                        .WithMany("Terminals")
                        .HasForeignKey("WindowId", "BranchId")
                        .HasPrincipalKey("Id", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("QControl.Domain.Entities.WaitingArea", b =>
                {
                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithMany("WaitingAreas")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Window", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "DeactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "LastModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ReactivatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QControl.Domain.Entities.WaitingArea", "WaitingArea")
                        .WithMany("Windows")
                        .HasForeignKey("WaitingAreaId", "BranchId")
                        .HasPrincipalKey("Id", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("DeactivatedByApplicationUser");

                    b.Navigation("LastModifiedByApplicationUser");

                    b.Navigation("ReactivatedByApplicationUser");

                    b.Navigation("WaitingArea");
                });

            modelBuilder.Entity("QControl.Domain.Identity.TechnicalAdmin", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("QControl.Domain.Identity.TechnicalAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.ApplicationUserBranch", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QControl.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.BranchAdmin", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Qcontrol.Domain.Identity.BranchAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("Qcontrol.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qcontrol.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Branding");

                    b.Navigation("Displays");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("WaitingAreas");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Display", b =>
                {
                    b.Navigation("DisplayWindows");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Service", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("QControl.Domain.Entities.ServiceWorkflow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("QControl.Domain.Entities.WaitingArea", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("QControl.Domain.Entities.Window", b =>
                {
                    b.Navigation("DisplayWindows");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Qcontrol.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
